// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGMVnh5R84V8xF1dTeERRuAdRuVpv-NxM',
    appId: '1:404662972712:web:bfc93a6fd245d23e3be01d',
    messagingSenderId: '404662972712',
    projectId: 'photo-journal-app-b0675',
    authDomain: 'photo-journal-app-b0675.firebaseapp.com',
    storageBucket: 'photo-journal-app-b0675.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-xXx7juxMN9jYs67nbTjTilT5ZzBorlY',
    appId: '1:404662972712:android:2af4a0cb47f708fc3be01d',
    messagingSenderId: '404662972712',
    projectId: 'photo-journal-app-b0675',
    storageBucket: 'photo-journal-app-b0675.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABoNdlC2Z3x_7DnyRFgo37yiGL06b2elk',
    appId: '1:404662972712:ios:9d3790317b6c61083be01d',
    messagingSenderId: '404662972712',
    projectId: 'photo-journal-app-b0675',
    storageBucket: 'photo-journal-app-b0675.firebasestorage.app',
    iosClientId: '404662972712-3vi363nvcelltdvsfu1et7bvkeo2mrr4.apps.googleusercontent.com',
    iosBundleId: 'com.example.photoJournalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABoNdlC2Z3x_7DnyRFgo37yiGL06b2elk',
    appId: '1:404662972712:ios:9d3790317b6c61083be01d',
    messagingSenderId: '404662972712',
    projectId: 'photo-journal-app-b0675',
    storageBucket: 'photo-journal-app-b0675.firebasestorage.app',
    iosClientId: '404662972712-3vi363nvcelltdvsfu1et7bvkeo2mrr4.apps.googleusercontent.com',
    iosBundleId: 'com.example.photoJournalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGMVnh5R84V8xF1dTeERRuAdRuVpv-NxM',
    appId: '1:404662972712:web:c1e02cb7ed17d21f3be01d',
    messagingSenderId: '404662972712',
    projectId: 'photo-journal-app-b0675',
    authDomain: 'photo-journal-app-b0675.firebaseapp.com',
    storageBucket: 'photo-journal-app-b0675.firebasestorage.app',
  );
}
